# 指定版本号
version: 0'2.0'
# 定义服务（类似于容器）
services:
   # 创建具体的服务（容器）
#   [MYSQL_CONTAINER_NAME]:
#     # 指定镜像名称
#     image:  maria[MYSQL_CONTAINER_NAME]:10.6.3
#     # 指定在运行容器时，传递的参数
#     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#     # 指定当前服务使用的数据卷
#     volumes:
#       - mysql_[MYSQL_CONTAINER_NAME]:/var/lib/mysql
#     environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#    #  ports:
#    #    - "13306:3306"

   [DJANGO_CONTAINER_NAME]:
     # 指定当前服务的依赖（前置）服务
#     depends_on:
#      - ${MYSQL_CONTAINER_NAME}
     # build指定Dockerfile所在路径
     build:
       context: ./django_app_docker
       args:
         PROJECT_NAME: ${DJANGO_PROJECT_NAME}
         MYSQL_CONTAINER_NAME: ${MYSQL_CONTAINER_NAME}
         MYSQL_USERNAME: ${MYSQL_USERNAME}
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
         MYSQL_DATABASE: ${MYSQL_DATABASE}
     # 指定构建后的镜像名称
     image: ghm/django_app:${DJANGO_IMAGE_TAG}
     # 指定重启策略
     restart: always
     volumes:
       - logs:/usr/src/app/logs/
       - django_code:/usr/src/app/${DJANGO_PROJECT_NAME}/

   [NGINX_CONTAINER_NAME]:
     depends_on:
       - $[DJANGO_CONTAINER_NAME]
     build:
       context: ./nginx_docker
       args:
         FRONT_END_PROJECT_NAME: ${FRONT_END_PROJECT_NAME}
         SERVER_ACCESS_ADDR: ${SERVER_ACCESS_ADDR}
         BACK_END_PORT: ${BACK_END_PORT}
         SERVER_ADDR: ${SERVER_ADDR}
         DJANGO_CONTAINER_NAME: ${DJANGO_CONTAINER_NAME}

     image: ghm/api-test-nginx:${WEB_IMAGE_TAG}
     restart: always
     ports:
       - "${FRONT_END_PORT}:80"
       - "${BACK_END_PORT}:8000"
     volumes:
       - logs:/var/log/nginx/
     environment:
       - SERVER_ADDR:${SERVER_ADDR}

#指定网络
networks:
  default:
    external:
      name: apirun_net

# 指定数据卷
volumes:
#    mysql_[MYSQL_CONTAINER_NAME]:
    django_code:
    logs:
