# 指定版本号
version: '2.0'

# 定义服务（类似于容器）
services:
   # 创建具体的服务（容器）
#   [MYSQL_CONTAINER_NAME]:
#     # 指定镜像名称
#     image:  maria[MYSQL_CONTAINER_NAME]:10.6.3
#     # 指定在运行容器时，传递的参数
#     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#     # 指定当前服务使用的数据卷
#     volumes:
#       - mysql_[MYSQL_CONTAINER_NAME]:/var/lib/mysql
#     environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#    #  ports:
#    #    - "13306:3306"

   rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

   django_app:
     # 指定当前服务的依赖（前置）服务
     depends_on:
      - rabbitmq
     # build指定Dockerfile所在路径
     build: ./django_app_docker
     # 指定构建后的镜像名称
     image: ghm/django_app:${DJANGO_IMAGE_TAG}
     # 指定重启策略
     restart: always
     volumes:
       - logs:/usr/src/app/logs/
       - django_code:/usr/src/app/${DJANGO_PROJECT_NAME}/

   web:
     depends_on:
       - django_app
     build: ./nginx_docker
     image: ghm/api-test-nginx:${WEB_IMAGE_TAG}
     restart: always
     ports:
       - "${WEB_EXPOSE_PORT}:80"
       - "${WEB_API_PORT}:8000"
     volumes:
       - logs:/var/log/nginx/
     environment:
       - SERVER_ADDR:${SERVER_ADDR}




#指定网络
networks:
  default:
    external:
      name: apirun_net

# 指定数据卷
volumes:
#    mysql_db:
    rmq:
    django_code:
    logs:

