# Generated by Django 3.2.7 on 2021-10-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcases',
            old_name='interfaces',
            new_name='interface',
        ),
    ]
