# Generated by Django 3.2.7 on 2021-10-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_rename_interfaces_testcases_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='include',
            field=models.TextField(help_text='用例执行前置顺序', null=True, verbose_name='前置条件'),
        ),
    ]
